### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by chrishoadley** [stigkristiansen/Netgear-Arlo#1]
Love the library!
I've been able to get the last still through "GetAllDevices".
Can you upload any examples or documentation using TakeSnapShot, GetLibrary, and Start/StopStream?

Sorry putting this through as an issue. Not sure if there is a way to message anymore.

**Comment by stigkristiansen** [comment]
Hi,
The library was created for personal usage, therefor no uploaded documentation.
The easiest way to use the library is to use the i/o module to populate all devices registered at the cloud service. Click on "Refresh" button. If you look at the code for TakeSnapshot at both the i/o-module and the camera-module you will see how Takesnapshot, GetLibrary and Start/StopStream are used. If you take a look at the script (_Snapshot) created by the i/o-module for each camera-module you will see an example of how to use TakeSnapshot.

**Comment by chrishoadley** [comment]
Thank you!
